// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCacheJob = "cache_job"

// PreheatJob mapped from table <preheat_job>
type CacheJob struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type        int32     `gorm:"column:type;not null" json:"type"`
	InstanceId  string    `gorm:"column:instance_id;not null" json:"instance_id"`
	Datatype    string    `gorm:"column:datatype;not null" json:"datatype"`
	Org         string    `gorm:"column:org;not null" json:"org"`
	Repo        string    `gorm:"column:repo;not null" json:"repo"`
	UsedStorage int64     `gorm:"column:used_storage;not null" json:"used_storage"`
	Commit      string    `gorm:"column:commit;not null" json:"commit"`
	Status      int32     `gorm:"column:status;not null" json:"status"`
	ErrorMsg    string    `gorm:"column:error_msg;not null" json:"error_msg"`
	Token       string    `gorm:"column:token;not null" json:"token"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PreheatJob's table name
func (*CacheJob) TableName() string {
	return TableNameCacheJob
}
