// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDingospeed = "dingospeed"

// Dingospeed mapped from table <dingospeed>
type Dingospeed struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	InstanceID string    `gorm:"column:instance_id;not null" json:"instance_id"`
	Host       string    `gorm:"column:host;not null" json:"host"`
	Port       int32     `gorm:"column:port;not null" json:"port"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Online     bool      `gorm:"column:online;not null;comment:是否在线" json:"online"` // 是否在线
}

// TableName Dingospeed's table name
func (*Dingospeed) TableName() string {
	return TableNameDingospeed
}
