// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHfToken = "hf_token"

// PreheatJob mapped from table <preheat_job>
type HfToken struct {
	ID    int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Token string `gorm:"column:token;not null" json:"token"`
}

// TableName PreheatJob's table name
func (*HfToken) TableName() string {
	return TableNameHfToken
}
