// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHfToken = "hf_token"

type HfToken struct {
	ID      int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Token   string `gorm:"column:token;not null" json:"token"`
	Enabled bool   `gorm:"column:enabled;not null;comment:是否启用" json:"enabled"`
}

// TableName PreheatJob's table name
func (*HfToken) TableName() string {
	return TableNameHfToken
}
