// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameModelFileRecord = "model_file_record"

// ModelFileRecord mapped from table <model_file_record>
type ModelFileRecord struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Datatype     string    `gorm:"column:datatype;not null" json:"datatype"`
	Org          string    `gorm:"column:org;not null" json:"org"`
	Repo         string    `gorm:"column:repo;not null" json:"repo"`
	Path         string    `gorm:"column:path;not null" json:"path"`
	DingospeedID int32     `gorm:"column:dingospeed_id;not null" json:"dingospeed_id"`
	CompleteAt   time.Time `gorm:"column:complete_at;not null;default:CURRENT_TIMESTAMP" json:"complete_at"`
}

// TableName ModelFileRecord's table name
func (*ModelFileRecord) TableName() string {
	return TableNameModelFileRecord
}
