// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameModelFileRecord1 = "model_file_record_1"

// ModelFileRecord1 mapped from table <model_file_record_1>
type ModelFileRecord1 struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Datatype  string    `gorm:"column:datatype;not null" json:"datatype"`
	Org       string    `gorm:"column:org;not null" json:"org"`
	Repo      string    `gorm:"column:repo;not null" json:"repo"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Etag      string    `gorm:"column:etag;not null" json:"etag"`
	FileSize  int64     `gorm:"column:file_size;not null" json:"file_size"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ModelFileRecord1's table name
func (*ModelFileRecord1) TableName() string {
	return TableNameModelFileRecord1
}
