// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePreheatJob = "preheat_job"

// PreheatJob mapped from table <preheat_job>
type PreheatJob struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	InstanceId string `gorm:"column:instance_id;not null" json:"instance_id"`
	Datatype   string `gorm:"column:datatype;not null" json:"datatype"`
	Org       string    `gorm:"column:org;not null" json:"org"`
	Repo      string    `gorm:"column:repo;not null" json:"repo"`
	Revision  string    `gorm:"column:revision;not null" json:"revision"`
	FileTotal int     `gorm:"column:file_total;not null" json:"file_total"`
	Status    int32     `gorm:"column:status;not null" json:"status"`
	MetaInfo  string    `gorm:"column:meta_info;not null" json:"meta_info"`
	Token  string    `gorm:"column:token;not null" json:"token"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PreheatJob's table name
func (*PreheatJob) TableName() string {
	return TableNamePreheatJob
}
