FROM golang:1.23.0 AS builder

LABEL stage=gobuilder

WORKDIR /app

COPY ./bin/dingoscheduler .

# Expose the 8090 port of the container for external acces
EXPOSE 9091

VOLUME /app/log

CMD ["./dingoscheduler"]
