// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dingoscheduler/internal/dao"
	"dingoscheduler/internal/data"
	"dingoscheduler/internal/handler"
	"dingoscheduler/internal/router"
	"dingoscheduler/internal/server"
	"dingoscheduler/internal/service"
	"dingoscheduler/pkg/app"
	"dingoscheduler/pkg/config"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func wireApp(configConfig *config.Config) (*app.App, func(), error) {
	echo := server.NewEngine()
	baseData, cleanup, err := data.NewBaseData(configConfig)
	if err != nil {
		return nil, nil, err
	}
	dingospeedDao := dao.NewDingospeedDao(baseData)
	modelFileRecordDao := dao.NewModelFileRecordDao(baseData)
	managerService := service.NewManagerService(dingospeedDao, modelFileRecordDao)
	managerHandler := handler.NewManagerHandler(managerService)
	sysService := service.NewSysService()
	sysHandler := handler.NewSysHandler(sysService)
	httpRouter := router.NewHttpRouter(echo, managerHandler, sysHandler)
	httpServer := server.NewHTTPServer(configConfig, httpRouter)
	schedulerServer := server.NewSchedulerServer(managerService)
	appApp := newApp(httpServer, schedulerServer)
	return appApp, func() {
		cleanup()
	}, nil
}
