// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dingoscheduler/internal/dao"
	"dingoscheduler/internal/data"
	"dingoscheduler/internal/handler"
	"dingoscheduler/internal/router"
	"dingoscheduler/internal/server"
	"dingoscheduler/internal/service"
	"dingoscheduler/pkg/app"
	"dingoscheduler/pkg/config"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func wireApp(configConfig *config.Config) (*app.App, func(), error) {
	echo := server.NewEngine()
	baseData, cleanup, err := data.NewBaseData(configConfig)
	if err != nil {
		return nil, nil, err
	}
	dingospeedDao := dao.NewDingospeedDao(baseData)
	modelFileRecordDao := dao.NewModelFileRecordDao(baseData)
	modelFileProcessDao := dao.NewModelFileProcessDao(baseData)
	repositoryTagDao := dao.NewRepositoryTagDao(baseData)
	repositoryDao := dao.NewRepositoryDao(baseData, repositoryTagDao)
	schedulerService := service.NewSchedulerService(baseData, dingospeedDao, modelFileRecordDao, modelFileProcessDao, repositoryDao)
	preheatJobDao := dao.NewPreheatJobDao(baseData)
	preheatJobService := service.NewPreheatJobService(dingospeedDao, modelFileProcessDao, preheatJobDao)
	tagDao := dao.NewTagDao(baseData)
	organizationDao := dao.NewOrganizationDao(baseData)
	organizationService := service.NewOrganizationService(organizationDao)
	repositoryService := service.NewRepositoryService(dingospeedDao, modelFileProcessDao, repositoryDao, tagDao, baseData, organizationDao, organizationService)
	managerHandler := handler.NewManagerHandler(schedulerService, preheatJobService, repositoryService)
	sysService := service.NewSysService()
	sysHandler := handler.NewSysHandler(sysService)
	tagService := service.NewTagService(tagDao)
	alayanewHandler := handler.NewAlayanewHandler(repositoryService, tagService)
	httpRouter := router.NewHttpRouter(echo, managerHandler, sysHandler, alayanewHandler)
	httpServer := server.NewHTTPServer(configConfig, httpRouter)
	schedulerServer := server.NewSchedulerServer(schedulerService)
	appApp := newApp(httpServer, schedulerServer)
	return appApp, func() {
		cleanup()
	}, nil
}
